### ISSUE TITLE
invisible svg 

### ISSUE THREAD

**Issue by darkworks** [mgieseki/dvisvgm#156] opened 2021-06-10 07:31 UTC
Hi thanks for this amazing tool

am trying to convert pdf page to svg , so i run this command
`dvisvgm --pdf input.pdf -p4`

it generated svg output file without any errors however the svg is invisible not showing any visual color in browser upon inspection i noticed that for some reason all paths **fill opacity** is set to 0 by default ?

update : attachment removed

thanks

**Comment by mgieseki** [comment] 2021-06-10 08:03
Please provide a minimal PDF file that can be used to reproduce the issue. Without the PDF data it's hard to tell what's triggering the opacity properties.

**Comment by darkworks** [comment] 2021-06-10 08:05
> Please provide a minimal PDF file that can be used to reproduce the issue. Without the PDF data it's hard to tell what's triggering the opacity properties.

ok can i have mail address so that i can send as its bit confidential

**Comment by darkworks** [comment] 2021-06-10 08:09
ok here is sample pdf please let me know when u download it 
[input_5.pdf](https://github.com/mgieseki/dvisvgm/files/6629511/input_5.pdf)

**Comment by mgieseki** [comment] 2021-06-10 08:12
I've downloaded the file, you can remove it. However, it's way to big for debugging. Could you please strip it down so that it only contains a single or few visual elements?

**Comment by darkworks** [comment] 2021-06-10 08:33
ok let me try if i can edit it

**Comment by darkworks** [comment] 2021-06-10 08:46
[sample_mini.zip](https://github.com/mgieseki/dvisvgm/files/6629772/sample_mini.zip)

ok please review this , it have pdf and svg

thanks

**Comment by mgieseki** [comment] 2021-06-11 09:39
The `fill-opacity` attributes are added if you use an old version of Ghostscript. You need at least version 9.52 because older releases lack the additional PostScript operators required to correctly detect transparency changes in PDF files. To determine the GS version dvisvgm is using on your machine, check the output of `dvisvgm -V1`.

There is an additional offset issue, though, which leads to displaced graphics if the lower left corner of the PDF file is not located at (0, 0). I'll fix that shortly.

**Comment by darkworks** [comment] 2021-06-11 11:00
thanks one more Question is there anyway we can specify output file path and name with it like --output=C:\mysvg.svg

**Comment by darkworks** [comment] 2021-06-11 12:02
i have run `dvisvgm -V1` command and it output this 
dvisvgm -V1
dvisvgm 2.11.1 (x86_64-pc-win64)
--------------------------------
brotli:      1.0.9
clipper:     6.2.1
fontforge:   20160721
freetype:    2.10.4
Ghostscript: 9.25
MiKTeX:      2.9
potrace:     1.16
ttfautohint: 1.8.3
xxhash:      0.8.0
zlib:        1.2.11

i checked my pc i have not installed Ghostscript: 9.25  , so am wondering this Ghostscript: 9.25 is installed by dvisvgm ? anyway to locate ghostscript 9.25 

in cmd i even run `gswin64c.exe`  `gswin64.exe` `gswinc.exe ` `gswinc.exe`  and it not triggered any ghost script version which mean its not even in my environment path . so am curious how dvisvgm  is using ghostscript as its using Environment variable or default program files installation path ?

**Comment by mgieseki** [comment] 2021-06-11 12:31
Since you're using MiKTeX, dvisvgm utilizes the Ghostscript DLL that comes with MiKTeX (`mgsdll32.dll` or `mgsdll64.dll`).
You can install a separate GS version and apply the corresponding DLL by setting environment variable `libgs`, e.g. `set libgs=\gs\gs9.54.0\bin\gsdll64.dll`.

**Comment by darkworks** [comment] 2021-06-12 07:29
one issue i found . i have installed dvisgm on my windows server 2019 and when i run 
```
dvisvgm -V1
dvisvgm 2.11.1 (x86_64-pc-win64)
--------------------------------

```

i get this ---------------- it  not displaying any information about ghostscript etc because i have set gslib flag on my server.

**Comment by mgieseki** [comment] 2021-06-12 09:50
If you don't get an input prompt again after calling dvisvgm, MiKTeX is probably updating some database files first. This usually happens after updating MiKTeX packages. You just have to wait until the maintenance stuff has finished.

**Comment by darkworks** [comment] 2021-06-12 09:52
hmmmm strange i waited almost 12 hours for it , as i tried it last night and now i tried but same no output , i will uninstall miktex and reinstall to see if it work

**Comment by mgieseki** [comment] 2021-06-12 09:53
Sometimes it helps to run `latex` first and wait until it finishes.

**Comment by darkworks** [comment] 2021-06-14 13:16
i had tested today svg outputs with ghost script 9.54 

```
dvisvgm 2.11.1 (x86_64-pc-win64)
--------------------------------
brotli:      1.0.9
clipper:     6.2.1
fontforge:   20160721
freetype:    2.10.4
Ghostscript: 9.54.0
MiKTeX:      2.9
potrace:     1.16
ttfautohint: 1.8.3
xxhash:      0.8.0
zlib:        1.2.11
```

and am still getting same output with opacity = 0

```
<path d='M63.597657 109.983974H60.335932V112.956635H63.597657Z' fill='#b87333' fill-opacity='0'/>
<path d='M58.917997 109.983974H55.656273V112.956635H58.917997Z' fill='#b87333' fill-opacity='0'/>
<path d='M63.597657 115.023036H60.335932V117.995697H63.597657Z' fill='#b87333' fill-opacity='0'/>
<path d='M58.917997 115.023036H55.656273V117.995697H58.917997Z' fill='#b87333' fill-opacity='0'/>
```

so can u please test it your end with gs9.54 with sample_mini.zip i send earlier 

thanks

**Comment by mgieseki** [comment] 2021-06-14 14:24
I tested both your reduced and the bigger PDF file. Both convert correctly regarding the opacity properties. I don't get the additional attributes when using GS 9.54.0. Are you sure, you checked the right SVG file?

**Comment by darkworks** [comment] 2021-06-14 18:33
hmmm found strange problem when i run **dvisvgm**  from cmd it use GS9.54  however when i convert pdf to svg using php through dvisvgm it use miktex default 9.25 ghost script.

```
		// PDF to SVG
		public function pdf_to_svg($parma){
			$command = $this->config['DVISVGM_BIN'].' -V1 ';
		//	$command = $this->config['DVISVGM_BIN'].' --pdf '.$parma->input_file.' --output='.$parma->output_file.' -p'.$parma->pdf_page_number.'';
			
			exec($command, $retArr, $retVal);
			
			 print_r($retArr); die();
			
			// verify converstion
			if(file_exists($parma->output_file)){
				return $parma->output_file;
			}else{
				return FALSE;
			}						
		
		} // method end
```
it output 
```
Array
(
    [0] => dvisvgm 2.11.1 (x86_64-pc-win64)
    [1] => --------------------------------
    [2] => brotli:      1.0.9
    [3] => clipper:     6.2.1
    [4] => fontforge:   20160721
    [5] => freetype:    2.10.4
    [6] => Ghostscript: 9.25
    [7] => MiKTeX:      2.9
    [8] => potrace:     1.16
    [9] => ttfautohint: 1.8.3
    [10] => xxhash:      0.8.0
    [11] => zlib:        1.2.11
)
```

so anyway we could just pass ghostscript bin location , seems like php under apache have not access to system environment vars.

also from cmd i did conversion of pdf  it do not have fill-opacity flag and when i open it in inkscape its not visible . can u please check the video i have attacked.

[small.zip](https://github.com/mgieseki/dvisvgm/files/6650509/small.zip)

**Comment by mgieseki** [comment] 2021-06-14 18:48
> so anyway we could just pass ghostscript bin location , seems like php under apache have not access to system environment vars.

I guess, you have to set the environment variable with PHP function `putenv()`. Alternatively, you can use dvisvgm's option `--libgs`.
 
> also from cmd i did conversion of pdf it do not have fill-opacity flag and when i open it in inkscape its not visible . can u please check the video i have attacked.

Yes, that's the graphics displacement I mentioned further above. If you scroll to the right in Inkscape, you'll find the missing graphics outside the viewport. I've already fixed this with changeset b0dd9ad038fd7e5325db9f021a795854b7bb4e49. It will be part of the next version of dvisvgm but there's no release date yet.

**Comment by darkworks** [comment] 2021-06-14 18:57
ok great , i will try to compile it for windows

**Comment by darkworks** [comment] 2021-06-15 05:52
am compiling source code using vs19 however am getting error

`Cannot open include file: 'ttfautohint.h': No such file or directory	dvisvgm`

however i have downloaded lib from [ ttfautohint-1.7.tar.gz ] : https://download.savannah.gnu.org/releases/freetype/
and extracted into dvisvgm-master\vc\ttfautohint

so any idea how to fix it. 
also this link u mentioned : https://github.com/mgieseki/ttfautohint-dll   does not have dll with it

**Comment by mgieseki** [comment] 2021-06-15 06:39
> also this link u mentioned : https://github.com/mgieseki/ttfautohint-dll does not have dll with it

Have a look at the _Releases_ section of that project. The zip archives contain all required files.

**Closed** 2021-06-15 18:43 UTC
