### ISSUE TITLE
Problem with ghostscript on Windows 64bit

### ISSUE THREAD

**Issue by ahmed-abdelhady** [mgieseki/dvisvgm#46] opened 2015-06-09 12:51 UTC
On Windows 64bit, dvisvgm fails to find ghostscript dll (64bit) automatically when placed in the same folder unless the path is given explicitly (either with  --libgs or the environment variable).

**Comment by mgieseki** [comment] 2015-07-11 19:09
Sorry for the late reply.
Unfortunately, I can't reproduce the issue. On my machines (Windows 7 and 8.1, both 64-bit) dvisvgm 1.9.2 finds `gsdll64.dll` if it's located in the same directory as `dvisvgm.exe`. It's important that you don't change the name of the DLL. Otherwise, you have to specify its path explicitly.

**Comment by mgieseki** [comment] 2015-09-14 06:51
I'm closing this ticket for now. If the problem persists, feel free to reopen it.

**Closed by mgieseki** 2015-09-14 06:51 UTC
