### ISSUE TITLE
Help with gradient problem

### ISSUE THREAD

**Issue by jsdodge** [mgieseki/dvisvgm#154] opened 2021-04-23 18:17 UTC
Running `latex + dvisvgm` or `pdflatex + dvisvgm --pdf` on the following MWE does not include the gradient in the SVG output. The bounding box has zero size, so it looks like it omits the entire rectangular element. Any suggestions for how to fix this? I'm using TeX Live 1.49 and GPL Ghostscript 9.53.3 on MacOS.

LaTeX MWE:
```latex
\documentclass{standalone}
\usepackage{tikz}

\begin{document}
\begin{tikzpicture}
\shade[left color=black, right color=white] (0,0) rectangle (10,10);
\end{tikzpicture}%

\end{document}
```

Output from `pdflatex` [here](https://github.com/mgieseki/dvisvgm/files/6367306/test.pdf).

Output from `dvisvgm --pdf`:
```svg
<?xml version='1.0' encoding='UTF-8'?>
<!-- This file was generated by dvisvgm 2.11.1 -->
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='0pt' height='0pt' viewBox='0 0 0 0'>
<defs/>
<g id='page1'/>
</svg>
```

**Comment by agrahn** [comment] 2021-04-23 18:56
`dvisvgm` does not support PostScript shadings and tiling patterns yet. For the time being, Tikz' `dvisvgm` driver can be used. It writes specials with SVG code in the intermediate DVI file:

````latex
\documentclass[dvisvgm]{standalone}

\usepackage{tikz}

\begin{document}
\begin{tikzpicture}
\shade[left color=black, right color=white] (0,0) rectangle (10,10);
\end{tikzpicture}%

\end{document}
````

**Comment by mgieseki** [comment] 2021-04-23 19:07
> `dvisvgm` does not support PostScript shadings and tiling patterns yet.

That's almost correct. ;-) dvisvgm does support tiling patterns but no shading ones. Only shading _fills_ (except axial and radial gradients) are supported.

**Comment by agrahn** [comment] 2021-04-23 19:09
> > `dvisvgm` does not support PostScript shadings and tiling patterns yet.
> 
> That's almost correct. ;-) dvisvgm does support tiling patterns but no shading ones. Only shading _fills_ (except axial and radial gradients) are supported.

Sorry, I wasn't sure. So I deleted my comment. I tried a tiling pattern recently and it didn't work. I try to find that example...

**Comment by mgieseki** [comment] 2021-04-23 19:26
No problem. There might still be bugs in the pattern code. I fixed one a couple of weeks ago. The patch is in the repo but isn't part of a release yet. If you find the hatch example that failed to convert, let me know.

**Comment by mgieseki** [comment] 2021-04-23 20:42
@jsdodge Alex' initial (now deleted) comment was right that the reason for the omitted pattern is dvisvgm's lacking support of shading patterns. As you can see in the following output of `mutool`, the gradient is defined as an axial shading pattern in the pdf file and therefore dvisvgm skips it:
```
$ mutool example.pdf
...
Shading patterns (1):
        1       (7 0 R):        Axial (0 0 R)
```

**Comment by jsdodge** [comment] 2021-04-23 21:10
OK, thanks. Please treat this as a suggested feature, then!

**Comment by mgieseki** [comment] 2021-04-23 21:28
It's already on my to-do list. 😉 However, PS and PDF allow for much more complex and flexible shading patterns than SVG and thus it's not possible to convert them easily. Some of the can't be represented by SVG elements at all and must be approximated as it's already done for [gradient fills](https://dvisvgm.de/Gradients).

**Closed** 2021-04-23 21:59 UTC

**Comment by agrahn** [comment] 2021-04-25 09:03
Here is a simple, TikZ-generated PostScript pattern that does not work. I am unsure whether I should open an issue:

````latex
\documentclass{article} 
 
\usepackage{tikz} 
\usetikzlibrary{patterns} 
%\def\pgfsysdriver{pgfsys-dvisvgm.def} 
 
\begin{document} 
Testing pattern: 
     
\begin{tikzpicture} 
    \fill[pattern = north east lines] (-2,2) rectangle (-2,-2); 
\end{tikzpicture} 
\end{document} 
````

**Comment by mgieseki** [comment] 2021-04-25 10:07
The problem here is that the area to be filled is 0 because the width of the rectangle is 0. In contrast to PostScript and PDF, SVG doesn't apply fill attributes in these cases. I guess I somehow have to emulate the behavior of PS/PDF.

**Comment by agrahn** [comment] 2021-04-25 12:05
> The problem here is that the area to be filled is 0 because the width of the rectangle is 0.
Oh sorry for that bad typo. I corrected the example, still no pattern in SVG but in the PS and PDF outputs.

**Comment by mgieseki** [comment] 2021-04-25 13:19
Ok, thanks for the update. There is indeed a bug in the released versions of dvisvgm that I already fixed in the repo (commit e1b1e71f286526582e9cc6f0e71232f48995063a). However, the extent of the tiles and the shape of the line ends are still not computed correctly which in this example causes visual gaps between the line segments.

**Comment by mgieseki** [comment] 2021-04-26 07:41
After having a closer look at the issue, I think commit e1b1e71f286526582e9cc6f0e71232f48995063a actually fixes it. The gaps between the tiles are caused by SVG renderers that ignore pattern attribute `overflow`.

Here's the SVG rendered with Firefox:
![shot1](https://user-images.githubusercontent.com/3620467/116045720-99b21700-a672-11eb-9d41-958fb278b39a.png)

And here is how it looks in Apache Batik which takes `overflow="visible"` into account:
![shot2](https://user-images.githubusercontent.com/3620467/116045726-9a4aad80-a672-11eb-9dab-4745237345c1.png)

**Comment by agrahn** [comment] 2021-04-26 08:22
Thank you, Martin, for clarifying. So I will try to compile dvisvgm from the git sources. And thank you for all your impressive work!
