### ISSUE TITLE
pdffile \special does not look into TeX search path

### ISSUE THREAD

**Issue by agrahn** [mgieseki/dvisvgm#103] opened 2019-04-03 14:14 UTC
Consider this MWE:

```latex
\documentclass{article}
\pagestyle{empty}

\begin{document}
  EPS:\makebox[320bp][l]{\rule{0pt}{240bp}%
    \special{PSfile="example-image-a.eps" llx=0 lly=0 urx=320 ury=240 rwi=3200}
  }\\
  PDF:\makebox[320bp][l]{\rule{0pt}{240bp}%
    \special{pdffile="example-image-a.pdf" llx=0 lly=0 urx=320 ury=240 rwi=3200}
  }
\end{document}

```

Both included graphic files are located in `{TEXMF}/tex/latex/mwe/` and thus found by `kpsewhich`. So does the `latex` command when run on the input file listed above.

But, when running `dvisvgm` on the DVI output, `dvisvgm` issues the following warning:

     WARNING: file 'example-image-a.pdf' not found

The second graphic is not shown in the SVG output, unless we put a copy of `example-image-a.pdf` into the current directory right before running `dvisvgm`.

**Comment by mgieseki** [comment] 2019-04-03 15:01
That's right. Until now I considered special `pdffile` an undocumented, internal extension and didn't expect anyone to use it directly. But there's no reason to keep it this way. Actually, it's pretty easy to add `.pdf` to the list of suffixes recognized by dvisvgm's file finder. I'll add a corresponding patch later today.

**Comment by agrahn** [comment] 2019-04-03 15:15
Thanks a lot! The next thing I will do is to open a pull request to https://github.com/latex3/graphics-def with an updated `dvisvgm.def` in order to add PS and PDF support to `graphic[xs]`.

BTW, how are the chances that the updated `dvisvgm` makes it into TL-19?

**Comment by mgieseki** [comment] 2019-04-03 15:34
> Thanks a lot! The next thing I will do is to open a pull request to https://github.com/latex3/graphics-def with an updated `dvisvgm.def` in order to add PS and PDF support to `graphic[xs]`.

Sounds great, I'm looking forward to it, and will try out the additions too, of course.

> BTW, how are the chances that the updated `dvisvgm` makes it into TL-19?

I refactored a lot of code for the upcoming release 2.7 to implement the new SVG optimizer and to also make it work with `dvisvgm:raw` fragments. I'm not sure if it would be a good idea to add this release to TL 2019 at such short notice because there could still be some regressions which then won't be fixed for a year.

**Closed** 2019-04-03 16:28 UTC
Labels: enhancement

**Comment by agrahn** [comment] 2019-04-09 14:22
> The next thing I will do is to open a pull request to https://github.com/latex3/graphics-def with an updated `dvisvgm.def` in order to add PS and PDF support to `graphic[xs]`.

Pull request submitted. In case you are interested:

https://github.com/latex3/graphics-def/pull/20#issuecomment-480237732

The zip file also contains `dvisvgm.def`, for testing purposes.
