### ISSUE TITLE
Hang with 100% CPU usage during parallel build in doc directory

### ISSUE THREAD

**Issue by ryandesign** [mgieseki/dvisvgm#171] opened 2021-12-24 14:18 UTC
dvisvgm (intermittently?) fails to build, with a `make` process using 100% CPU, if the doc directory is built in parallel (e.g. with `-j8`).

This was [reported to MacPorts in 2018](https://trac.macports.org/ticket/57528) where the problem was worked around by disabling parallel builds, but this is not ideal since dvisvgm takes some time to build and benefits from a parallel build.

The problem is easy to reproduce, on my macOS 10.15.7 system at least. After running `./configure`, `cd` to the doc directory and `make -j8`:

```
$ cd doc
$ make -j8
sed -e 's/@VERSION[@]/2.12/g' -e 's/@PACKAGE_BUGREPORT[@]/martin.gieseking@uos.de/g' dvisvgm.txt.in >dvisvgm.txt
if [ dvisvgm.txt.in -nt ../configure.ac ]; \
	then touch -r dvisvgm.txt.in dvisvgm.txt; \
	else touch -r ../configure.ac dvisvgm.txt; \
	fi
```

The build process hangs here forever with `make` using 100% CPU.

Interrupting the process with Control-C and trying again succeeds immediately with nothing to do:

```
$ make -j8
make: Nothing to be done for `all'.
```

If I reset things and try again, this time using `make` instead of `make -j8` in the doc directory, it finishes successfully immediately after the `if` statement that `touch`es the file.

The problem first appeared in MacPorts right after the dvisvgm port was updated to 2.6.1, which is the first version to include d1fa528f81b7dfc5b21f096c1aa8de68e870a92c which added the code that `touch`es dvisvgm.txt, so I suspect that change is the cause. If I revert that change, the problem goes away:

```
$ make -j8
asciidoc -a icons -a 'iconsdir=.' -a badges -a 'revnumber=2.12' --unsafe -bdocbook -dmanpage -o dvisvgm-man.xml.tmp dvisvgm.txt
xsltproc -o dvisvgm-man.xml ../doc/tweak-db-refentry.xsl dvisvgm-man.xml.tmp
rm dvisvgm-man.xml.tmp
xmlto -m ../doc/conf-dblatex-man.xsl --stringparam man.endnotes.list.enabled=0 --stringparam man.endnotes.are.numbered=0 --stringparam man.authors.section.enabled=0 man dvisvgm-man.xml
Note: Writing dvisvgm.1
```

Of course, that goes back to updating the manpage even when it is not needed, so perhaps a different solution to that can be found.

**Comment by ryandesign** [comment] 2021-12-24 14:23
The above was with /usr/bin/make on macOS, which is Apple's probably patched version of GNU make 3.81.

If I instead use /opt/local/bin/gmake from MacPorts, which is GNU make 4.3, then the problem does not occur.

However, compatibility with Apple's GNU make 3.81 is desirable, since that is the version included with Apple's developer tools. Apple will not update to any newer versions of GNU make, since they are under the GPL 3 license, to which Apple has an aversion.

**Comment by ryandesign** [comment] 2021-12-24 14:32
I noticed your GitHub workflow builds dvisvgm serially. You may want to have it build in parallel, both to save time and to verify that parallel builds work properly.

**Comment by ryandesign** [comment] 2021-12-24 15:00
Using `make`'s `-d` flag to get debug output, I see that after the `if` statement to `touch` the file, make 3.81 is in the following infinite loop:

```
Considering target file `all'.
 File `all' does not exist.
  Considering target file `all-am'.
   File `all-am' does not exist.
    Considering target file `Makefile'.
    File `Makefile' was considered already.
    Considering target file `dvisvgm.1'.
       Considering target file `dvisvgm.txt'.
       File `dvisvgm.txt' was considered already.
       Considering target file `../doc/tweak-db-refentry.xsl'.
       File `../doc/tweak-db-refentry.xsl' was considered already.
      Considering target file `../doc/conf-dblatex-man.xsl'.
      File `../doc/conf-dblatex-man.xsl' was considered already.
     Finished prerequisites of target file `dvisvgm.1'.
    The prerequisites of `dvisvgm.1' are being made.
   Finished prerequisites of target file `all-am'.
  The prerequisites of `all-am' are being made.
 Finished prerequisites of target file `all'.
The prerequisites of `all' are being made.
```

while make 4.3 just does:

```
Considering target file 'all'.
 File 'all' does not exist.
  Considering target file 'all-am'.
   File 'all-am' does not exist.
    Considering target file 'Makefile'.
    File 'Makefile' was considered already.
    Considering target file 'dvisvgm.1'.
       Considering target file 'dvisvgm.txt'.
       File 'dvisvgm.txt' was considered already.
       Considering target file '../doc/tweak-db-refentry.xsl'.
       File '../doc/tweak-db-refentry.xsl' was considered already.
      Considering target file '../doc/conf-dblatex-man.xsl'.
      File '../doc/conf-dblatex-man.xsl' was considered already.
     Finished prerequisites of target file 'dvisvgm.1'.
     Prerequisite 'dvisvgm-man.xml' of target 'dvisvgm.1' does not exist.
     Prerequisite '../doc/conf-dblatex-man.xsl' is older than target 'dvisvgm.1'.
    No need to remake target 'dvisvgm.1'.
   Finished prerequisites of target file 'all-am'.
  Must remake target 'all-am'.
  Successfully remade target file 'all-am'.
 Finished prerequisites of target file 'all'.
Must remake target 'all'.
Successfully remade target file 'all'.
```

**Comment by ryandesign** [comment] 2021-12-24 20:17
@kencu suggests that this change fixes the problem:
```diff
$ cat patch-dvisvgm-parallel-make-hang.diff
--- doc/Makefile.am.orig	2021-12-24 11:51:24.000000000 -0800
+++ doc/Makefile.am	2021-12-24 11:51:45.000000000 -0800
@@ -73,6 +73,8 @@
 dvisvgm.sty: dvisvgm-man.xml $(GEN_DBLATEX_STY)
 	xsltproc -o dvisvgm.sty $(GEN_DBLATEX_STY) $<
 
+.NOTPARALLEL:
+
 dvisvgm.txt: dvisvgm.txt.in ../configure.ac
 	sed -e 's/@VERSION[@]/@VERSION@/g' -e 's/@PACKAGE_BUGREPORT[@]/@PACKAGE_BUGREPORT@/g' $< >$@
 	if [ $< -nt ../configure.ac ]; \
```
I don't know if it is the best solution, just passing it along.

**Comment by kencu** [comment] 2021-12-24 20:59
thanks, @ryandesign -- indeed that does work for me, and it is a recognized gmake fix for this kind of issue if a more elegant dependency-style fix that doesn't require this can't be discovered. Best! K

**Comment by mgieseki** [comment] 2022-01-10 09:53
Thanks for the detailed report and for the suggested fix. Unfortunately, I can't reproduce the issue on my Linux machines. Although I build the sources in parallel all the time, it has never occurred to me. However, I don't have a Mac available and can't test the builds there. I'll add `.NOTPARALLEL` as suggested and hope it will fix the the issue.

**Comment by ryandesign** [comment] 2022-01-10 18:07
> I can't reproduce the issue on my Linux machines

With what version of GNU make? :) I expect your Linux machines probably have up-to-date versions of GNU make that don't experience the problem.

**Comment by mgieseki** [comment] 2022-01-10 19:00
Yes, that's right. The oldest one is gmake 4.1 on a dated Ubuntu system, though, which is from 2014.
If `.NOTPARALLEL` fixes the problem, I'd rather not install and play around with older versions of gmake to find a smarter solution. :-)

**Comment by ryandesign** [comment] 2022-01-10 19:30
> If `.NOTPARALLEL` fixes the problem

Yes it does fix it for us in MacPorts.

**Closed** 2022-01-11 10:26 UTC
