### ISSUE TITLE
Circle is missing in the output when converting from pdf

### ISSUE THREAD

**Issue by scrouthtv** [mgieseki/dvisvgm#150] opened 2021-03-24 11:42 UTC
Hello,

I'm trying to convert circuit drawings created with `circuitikz` to svg. However, the output is missing some things.

Compiling this tex:
```
\documentclass[margin = 24mm]{standalone}

\usepackage{xcolor, circuitikz}

\begin{document}
	\begin{circuitikz}
		\draw (0, 0) to [short, o-*] (1, 0);
	\end{circuitikz}
\end{document}
```
gives me this pdf:
![image](https://user-images.githubusercontent.com/23227405/112304162-73791000-8c9d-11eb-94aa-31334a8042c4.png)
(notice the empty and filled circle on the end of the line)

If I convert this to svg using
```
dvisvgm --pdf circle.pdf
```
I get a line with no tips:
![image](https://user-images.githubusercontent.com/23227405/112304708-1762bb80-8c9e-11eb-9ba7-92f6f89fec29.png)

**However**, if I first convert the pdf to ps using poppler, and then convert the ps to svg:
```
pdftops circle.pdf
dvisvgm --eps circle.ps
```
![image](https://user-images.githubusercontent.com/23227405/112304857-4842f080-8c9e-11eb-88c5-1de7cdf4dfd2.png)

I wasn't able to figure out, how exactly the `*-o` is drawn by circuitikz, and normal circles drawn with tikz work as expected.

Thanks for any help in advance.

**Comment by mgieseki** [comment] 2021-03-24 11:52
Unfortunately, I can't reproduce the issue. The file converts correctly with the latest version.
What version of dvisvgm and Ghostscript do you use? Could you post the output of `dvisvgm -V1`?

**Comment by scrouthtv** [comment] 2021-03-24 14:47
```
dvisvgm 2.9.1
-------------
brotli:      1.0.7
clipper:     6.2.1
fontforge:   20160721
freetype:    2.10.4
Ghostscript: 95.33
kpathsea:    6.3.2
potrace:     1.16
xxhash:      0.7.3
zlib:        1.2.11
```

**Comment by scrouthtv** [comment] 2021-03-24 15:13
Oh wow, my dvisvgm version is heavily outdated. It came preinstalled with my distribution's TexLive package, I'll look into it.

**Comment by mgieseki** [comment] 2021-03-24 15:17
Ok, thanks. This is the same issue as in #139. It's related to changes introduced with Ghostscript 9.52 which dvisvgm 2.9.1 doesn't support. It was fixed in 2.10. You could either update to a newer release of dvisvgm if possible, or install an older version of Ghostscript alongside the recent one.

**Comment by scrouthtv** [comment] 2021-03-24 15:17
Thanks for the quick help!

**Comment by mgieseki** [comment] 2021-03-24 15:17
You're welcome. Feel free to report any further issues.

**Closed** 2021-03-24 15:17 UTC

**Comment by scrouthtv** [comment] 2021-03-24 15:25
Do you, by any chance, know, when the update will make it's way to TexLive? I just installed TL [from upstream](https://www.tug.org/texlive/acquire-netinstall.html) and still only got dvisvgm 2.9.1.

**Comment by mgieseki** [comment] 2021-03-24 16:07
Yes, TL updates the binaries only once a year with each big release. Only packages that don't require individual builds for all supported target platforms get intermediate updates. More recent versions of programs like dvisvgm normally have to be rebuilt by the users themselves.
