### ISSUE TITLE
dvisvgm did not produce svg file `PostScript error: typecheck in setpattern`

### ISSUE THREAD

**Issue by HiTuX** [mgieseki/dvisvgm#155] opened 2021-05-09 20:02 UTC
dvisvgm version 2.9.1 shipped with texlive-bin  2020.54586-14 from artixlinux repo
(I built the latest release from source ang got the same error)
```
$ dvidvgm -o tmp.svg file.dvi 
pre-processing DVI file (format version 2)
processing page 1
  PostScript error: typecheck in setpattern
  Operand stack:
      --nostringval--
```
any hints?

**Comment by mgieseki** [comment] 2021-05-09 20:49
Please post a small LaTeX example that can be use to reproduce the issue. What sources did you use to build dvisvgm? Those from the Git repository or the ones in the 2.11.1 release archive?

**Comment by HiTuX** [comment] 2021-05-10 04:33
@mgieseki  
Actually, the LaTeX file  is a complicated one, as I was trying emacs' package [https://github.com/dandavison/xenops](xenops)  on my thesis ( my fault :-( ).  I found that commenting `\usepackage{todonotes}` fix the problem.
here is a minimal working example:  http://ix.io/3mmn (works fine else `todonotes` package is used)
``` latex
\documentclass{standalone}
\usepackage{todonotes}
\begin{document}
$\Delta_{cf}$
\end{document}
```

**Comment by HiTuX** [comment] 2021-05-12 08:17
here is a the [dvi file](https://drop.infini.fr/r/v9CDqgr4qH#p7M6pI/fu9omcweUyFdUKk6bAuOp8aBSY3Q5qYtXB3g=) created from the minimal code above on my machine.

**Comment by mgieseki** [comment] 2021-05-12 08:44
Ok, thanks. Now I'm able to reproduce the error. The bug is already fixed in the repository (commit 859da7c30db3ec19a30f06aecaa3f309767b5906) but it's not yet part of a release. If you clone the repository and build dvisvgm from there, the issue should go away.

**Comment by HiTuX** [comment] 2021-05-12 12:18
Thank you for your help. 
I clone the repository and build dvisvgm. I could produce the svg file from dvi, but something is wrong with svg: I got a black box.

here is the [dvi file](https://drop.infini.fr/r/8S3bShZu8S#4S0HNK4Y3U/UnJCERVVGTI60rXsgDw0mBP3EFBfpcKA=) the [produced svg file](https://drop.infini.fr/r/H_fbxGaUH9#3OOq/7o1q5O9LBG06k0auMNxWbQ1FaFx+EzqfKZqsOM=) and a screen shoot of what I got with `xenops` on emacs: 
![20210512_131336_region](https://user-images.githubusercontent.com/6303262/117973379-3d165380-b324-11eb-9e3c-90c5f93b6bbb.png)

**Comment by mgieseki** [comment] 2021-05-12 16:00
Yes, that's expected behavior in this case. Since dvisvgm doesn't support shading patterns yet, it doesn't evaluate the corresponding parameters at all. The file contains 4 such patterns used to fill a square on which the characters are printed. Instead of filling the square with the color gradient defined by the pattern (which is plain white here), dvisvgm fills it with the default color black. I don't know why the patterns are present at all. Maybe that's a default of the `todonotes` package.
So, at the moment, the only fix is to somehow remove the PGF code from the LaTeX sources that creates the invisible squares. Maybe it can also help to update the included LaTeX packages because there are no black squares when I convert the DVI files produced on my system.

**Comment by mgieseki** [comment] 2021-05-15 06:52
I just found some time to dig a bit deeper into the DVI file and the PS specials it contains and was surprised to find out that dvisvgm converts the file correctly. The shading patterns don't hurt here. Actually, the result of `dvisvgm --bbox=papersize sample-2` looks exactly the same as the PS file created with `dvips sample-2`. The black text is shown on top of a black rectangle. So, the issue is in the `.tex` file or the included packages and not in dvisvgm.

**Closed** 2021-05-22 21:45 UTC
Labels: already fixed
