### ISSUE TITLE
alternating colors on table rows corrupts dvisvgm output

### ISSUE THREAD

**Issue by libBletchley** [mgieseki/dvisvgm#76] opened 2017-09-18 14:43 UTC
This code produces a perfectly fine `.dvi` file that contains a table in color, but it gets hosed when `dvisvgm` processes it:
```
\documentclass[12pt]{minimal}
\usepackage[margin=0mm,nofoot,nohead,a5paper,landscape]{geometry}
\usepackage[active,tightpage]{preview}
\usepackage[table,dvipsnames,svgnames]{xcolor} % loads also »colortbl«

\begin{document}
\begin{preview}
  \fontsize{0.75cm}{0.8cm}\selectfont 
  \centerline{\underline{experiment}}
  \rowcolors{2}{Khaki}{Moccasin} %this line causes dvisvgm to hose things
  \begin{tabular}{l}
    \textsl{\textbf{col name}}\\
    foo\\
    bar\\
    baz\\
  \end{tabular}
\end{preview}
\end{document}
```
Specifically, the last two rows of the table ("bar" and "baz") do not appear.  Commenting out the `\rowcolors` line gives no problems for `dvisvgm`.

**Comment by mgieseki** [comment] 2017-09-18 14:53
I can't reproduce the issue at the moment. According to your information in #75, you're using a 3 years old version of dvisvgm (1.8.1) that obviously doesn't handle color specials properly. However, the issue has been fixed in the meantime.

**Comment by libBletchley** [comment] 2017-09-18 15:04
thanks, i'll try compiling the current version then.

**Closed** 2017-09-18 17:09 UTC
