### ISSUE TITLE
Several issues with TikZ pictures

### ISSUE THREAD

**Issue by matteoipri** [mgieseki/dvisvgm#148] opened 2021-02-26 09:59 UTC
Hi,
While typesetting some LaTeX documents with `tikzpicture`s in them to HTML, using tex4ht and [dvisvgm4ht](https://github.com/michal-h21/dvisvgm4ht), I found out that some graphical elements where not rendered correctly.
I thought it was an issue with tex4ht but I am able to reproduce the issues using regular `latex` and `dvisvgm`.

Here is the MWE:
```latex
\documentclass[border=10pt]{standalone}
\usepackage{tikz}
\begin{document}
\begin{tikzpicture}
\fill[red, opacity=0.4] (0,0) circle (4pt);
\node[color=red, opacity=0.4] at (1,0) {M};
\end{tikzpicture}
\end{document}
```

When I use the command `latexmk -pdf m.tex`, I get the following (to my eyes) correct rendering:
![image](https://user-images.githubusercontent.com/695348/109284021-b3281580-781f-11eb-85c2-ec2f6d96988a.png)

I then compile the document without the `-pdf` option in order to get the DVI file to be converted to SVG with `dvisvgm m.dvi`, which gets me the following (when opened with Chromium):
![image](https://user-images.githubusercontent.com/695348/109284278-f84c4780-781f-11eb-992a-fc7c0383c4a2.png)
The issue here is that the "M" is not getting the opacity setting.
Here is the content of the generated file "m-1.svg":
```xml
<?xml version='1.0' encoding='UTF-8'?>
<!-- This file was generated by dvisvgm 2.9.1 -->
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='36.899694pt' height='7.96875pt' viewBox='-62.03906 -59.29687 36.899694 7.96875'>
<defs>
<font id='cmr10' horiz-adv-x='0'>
<font-face font-family='cmr10' units-per-em='1000' ascent='750' descent='250'/>
<glyph unicode='M' horiz-adv-x='916' vert-adv-y='916' glyph-name='M' d='M241 661C232 683 229 683 206 683H37V652H61C138 652 140 641 140 605V105C140 78 140 31 37 31V0C72 1 121 3 154 3S236 1 271 0V31C168 31 168 78 168 105V644H169L410 22C415 9 420 0 430 0C441 0 444 8 448 19L694 652H695V78C695 42 693 31 616 31H592V0C629 3 697 3 736 3S842 3 879 0V31H855C778 31 776 42 776 78V605C776 641 778 652 855 652H879V683H710C684 683 684 682 677 664L458 101L241 661Z'/>
</font>
</defs>
<style type='text/css'>
<![CDATA[text.f0 {font-family:cmr10;font-size:9.96264px}
]]>
</style>
<g id='page1'>
<path d='M-54.06641-55.312499C-54.06641-57.51562-55.85156-59.29687-58.050782-59.29687C-60.25391-59.29687-62.03906-57.51562-62.03906-55.312499C-62.03906-53.11328-60.25391-51.32812-58.050782-51.32812C-55.85156-51.32812-54.06641-53.11328-54.06641-55.312499Z' fill='#f00' fill-opacity='.4'/>
<text class='f0' x='-58.052308' y='-55.312947' transform='matrix(1 0 0 1 23.7805 3.4039)'>
<tspan fill='#f00'>M</tspan>
</text>
</g>
</svg>
```

Compiling with tex4ht I get a visually similar result but with different SVG code:
![image](https://user-images.githubusercontent.com/695348/109284930-b66fd100-7820-11eb-8e22-6f2fd89a1bec.png)
```xml
<?xml version='1.0' encoding='UTF-8'?>
<!-- This file was generated by dvisvgm 2.9.1 -->
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='51.121842pt' height='11.161724pt' viewBox='-41.917974 -82.982816 51.121842 11.161724'>
<defs>
<path id='g3-77' d='M.368618-6.814446V-6.505604C.498132-6.505604 .627646-6.515567 .747198-6.515567C1.105853-6.515567 1.39477-6.465753 1.39477-6.067248V-1.026152C1.39477-.37858 .797011-.318804 .368618-.318804V-.009963H2.699875V-.318804C2.251557-.318804 1.663761-.37858 1.663761-1.066002C1.663761-1.155666 1.673724-1.255293 1.673724-1.344956L1.683686-6.445828C1.733499-6.236613 1.833126-6.03736 1.912827-5.838107C2.610212-3.995019 3.327522-2.161893 4.044832-.33873C4.084682-.229141 4.134496-.009963 4.283935-.009963H4.293898C4.443337-.029888 4.483188-.259029 4.533001-.37858C5.250311-2.241594 5.997509-4.124533 6.704857-5.997509C6.774595-6.166874 6.854296-6.336239 6.90411-6.515567L6.914072-.767123C6.914072-.368618 6.595268-.308842 6.276463-.308842C6.136986-.308842 6.007472-.318804 5.88792-.318804V-.009963H8.747198V-.318804C8.627646-.318804 8.498132-.308842 8.37858-.308842C8.029888-.308842 7.721046-.358655 7.721046-.747198V-6.067248C7.721046-6.455791 8.039851-6.515567 8.37858-6.515567C8.508095-6.515567 8.637609-6.505604 8.747198-6.505604V-6.814446H7.013699L6.824408-6.784558L6.724782-6.625156L4.562889-1.016189L2.391034-6.625156L2.291407-6.784558L2.102117-6.814446H.368618Z'/>
</defs>
<g id='page1' transform='matrix(1.4 0 0 1.4 0 0)'>
<path d='M-21.96875-55.285157C-21.96875-57.48828-23.75391-59.27344-25.953125-59.27344C-28.15625-59.27344-29.94141-57.48828-29.94141-55.285157C-29.94141-53.08594-28.15625-51.30078-25.953125-51.30078C-23.75391-51.30078-21.96875-53.08594-21.96875-55.285157Z' fill='#f00' fill-opacity='.4'/>
<g fill='#f00' transform='matrix(1 0 0 1 23.78165 3.4308)'>
<use x='-25.954657' y='-55.286921' xlink:href='#g3-77'/>
</g>
</g>
</svg>
```

Following the same procedure above (`latexmk` to get the DVI and `dvisvgm` (standalone or through `tex4ht`) to get the SVG) I got the following typesetting the official [Venn diagram example](https://texample.net/tikz/examples/venn/) from the TikZ website:
![image](https://user-images.githubusercontent.com/695348/109285428-5d546d00-7821-11eb-882d-a211f69ad346.png)

Are these "bugs" in `dvisvgm` or am I doing something wrong?

Thank you for your attention,
Matteo

**Comment by agrahn** [comment] 2021-02-26 13:00
Transparency is supported in newer dvisvgm versions (2.10+). You may want to install TexLive-2021-pretest (open since today) to make use of transparency features https://www.tug.org/texlive/pretest.html

**Comment by mgieseki** [comment] 2021-02-26 13:38
Transparency is indeed limited to PS graphics objects at the moment. The corresponding properties are not yet propagated to text elements or other components created outside the PS handler. It's on my to-do list and still needs some work.

I need to investigate the positioning issue in more detail. There's probably a conflict between DVI and PS coordinates that hasn't occurred until now. However, I can't reproduce the misaligned letters e.g. in "Typography". This seems to be fixed in the recent version.

**Comment by agrahn** [comment] 2021-02-26 13:55
> I can't reproduce the misaligned letters e.g. in "Typography".

I think this one goes away with `--font-format=woff2`.

**Comment by mgieseki** [comment] 2021-02-26 14:01
> I think this one goes away with `--font-format=woff2`.
Yes, hopefully. But it shouldn't occur with `--no-fonts` either which was maybe used in the example. Otherwise, the wrong alignment is expected with most SVG renderers due to lacking SVG font support.

**Comment by mgieseki** [comment] 2021-02-26 14:35
I just played around a bit more with the second example and it's actually converted correctly -- at least according to the current implementation of PS specials. If you convert the Venn example with dvips, you get the exact same result (modulo transparency) as with dvisvgm. The example probably makes use of PDF extensions not yet supported by dvisvgm. I have to dig a bit deeper into the PGF stuff to find out what these are.

**Comment by mgieseki** [comment] 2021-02-28 09:37
The wrong conversion of the Venn diagram is actually a [PGF issue](https://github.com/pgf-tikz/pgf/issues/995). There's already a proposed fix.

**Closed** 2021-03-15 13:19 UTC

**Comment by mgieseki** [comment] 2021-03-15 13:27
The latest version in the master branch should now apply transparency settings to all text and graphics elements that are created outside the PS handler. However, due to limitations of older GS releases, this only works correctly as of GS 9.52.
